/**
 * Shared PGlite migration utilities.
 *
 * Drizzle Kit / drizzle-orm/pglite do not support running Drizzle's own
 * migration SQL on PGlite (WASM in-process) because drizzle-kit migrate
 * requires a real TCP-based PostgreSQL server.
 *
 * These functions read the raw SQL migration files generated by
 * `drizzle-kit generate` and apply them directly via PGlite.exec().
 * All statements are wrapped for idempotency (CREATE IF NOT EXISTS,
 * DO blocks for CREATE TYPE and ALTER TABLE ... ADD CONSTRAINT)
 * so they are safe to re-run on every startup.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Returns all Drizzle PG migration SQL file paths sorted by version.
 *
 * @returns Sorted array of absolute file paths to migration .sql files
 */
export function getMigrationFiles(): string[] {
  const migrationsDir = resolve(import.meta.dir, "../../../drizzle");

  if (!existsSync(migrationsDir)) return [];

  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  return files.map((f) => resolve(migrationsDir, f));
}

/**
 * Wraps CREATE TYPE statements in DO blocks for idempotency.
 *
 * Without this wrapper, re-running a migration that contains
 * CREATE TYPE would fail with "type already exists".
 *
 * @param sql - Raw SQL statement
 * @returns SQL with CREATE TYPE wrapped in DO $$ ... EXCEPTION WHEN duplicate_object
 */
function wrapCreateType(sql: string): string {
  return sql.replace(
    /^(CREATE\s+TYPE\s+.+?;)$/gm,
    (match) => `DO $$ BEGIN\n  ${match}\nEXCEPTION WHEN duplicate_object THEN null;\nEND $$;`,
  );
}

/**
 * Wraps ALTER TABLE ... ADD CONSTRAINT with a pg_constraint existence check.
 *
 * PostgreSQL does not support IF NOT EXISTS for constraints, so we use
 * a DO block to check pg_constraint before adding.
 *
 * @param sql - Raw SQL statement
 * @returns SQL with ALTER TABLE ... ADD CONSTRAINT wrapped in idempotent DO block
 */
function wrapAddConstraint(sql: string): string {
  return sql.replace(
    /^ALTER\s+TABLE\s+\S+\s+ADD\s+CONSTRAINT\s+"([^"]+)".*;$/gm,
    (match, conName) =>
      `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${conName}') THEN ${match} END IF; END $$;`,
  );
}

/**
 * Applies idempotency wrappers to migration SQL so it is safe to re-run.
 *
 * Currently handles:
 *  - CREATE TYPE (wrapped in DO $$ ... EXCEPTION WHEN duplicate_object)
 *  - CREATE TABLE (replaced with CREATE TABLE IF NOT EXISTS)
 *  - ALTER TABLE ... ADD CONSTRAINT (wrapped in DO $$ with pg_constraint check)
 *
 * @param sql - Raw SQL statement from a migration file
 * @returns Idempotent SQL safe for re-execution
 */
export function wrapStatements(sql: string): string {
  let result = wrapCreateType(sql);
  result = result.replace(/^CREATE\s+TABLE\s+/i, "CREATE TABLE IF NOT EXISTS ");
  result = wrapAddConstraint(result);
  return result;
}

/**
 * Applies a single migration SQL file against a PGlite-compatible client.
 *
 * Each statement is split on the Drizzle "--> statement-breakpoint" delimiter,
 * wrapped for idempotency via {@link wrapStatements}, and executed sequentially.
 * Errors are silently caught — the wrappers ensure idempotency, so failures
 * on re-runs are expected and harmless.
 *
 * @param client - PGlite-like client with an exec() method
 * @param filePath - Absolute path to the migration .sql file
 */
export async function applyMigrationFile(
  client: { exec(sql: string): Promise<unknown> },
  filePath: string,
): Promise<void> {
  const sql = readFileSync(filePath, "utf-8");
  const statements = sql
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter(Boolean);

  for (const raw of statements) {
    const stmt = wrapStatements(raw);
    try {
      await client.exec(stmt);
    } catch {
      // Silently skip — wrappers ensure idempotency for re-runs
    }
  }
}

/**
 * Runs all pending Drizzle migration files against a PGlite-compatible client.
 *
 * Iterates over all sorted migration .sql files from the drizzle/ directory
 * and applies each one via {@link applyMigrationFile}.
 *
 * @param client - PGlite-like client with an exec() method
 */
export async function runAllMigrations(client: {
  exec(sql: string): Promise<unknown>;
}): Promise<void> {
  const files = getMigrationFiles();
  for (const filePath of files) {
    await applyMigrationFile(client, filePath);
  }
}