import type { accounts } from "./accounts";
import type { mcpApiKeys } from "./mcpApiKeys";
import type { permissions } from "./permissions";
import type { roles } from "./roles";
import type { rolePermissions } from "./rolePermissions";
import type { serviceHealth } from "./serviceHealth";
import type { sessions } from "./sessions";
import type { subscriptionPlans } from "./subscriptionPlans";
import type { subscriptions } from "./subscriptions";
import type { tasks } from "./tasks";
import type { userRoles } from "./userRoles";
import type { users } from "./users";
import type { userSettingsAccount } from "./userSettingsAccount";
import type { userSettingsDisplay } from "./userSettingsDisplay";
import type { userSettingsNotifications } from "./userSettingsNotifications";
import type { userSettingsProfile } from "./userSettingsProfile";
import type { verifications } from "./verifications";

export type User = typeof users.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type Account = typeof accounts.$inferSelect;
export type Verification = typeof verifications.$inferSelect;
export type McpApiKey = typeof mcpApiKeys.$inferSelect;
export type ServiceHealth = typeof serviceHealth.$inferSelect;
export type SubscriptionPlan = typeof subscriptionPlans.$inferSelect;
export type Subscription = typeof subscriptions.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;
export type UserSettingsProfile = typeof userSettingsProfile.$inferSelect;
export type UserSettingsAccount = typeof userSettingsAccount.$inferSelect;
export type UserSettingsDisplay = typeof userSettingsDisplay.$inferSelect;
export type UserSettingsNotifications = typeof userSettingsNotifications.$inferSelect;
export type Permission = typeof permissions.$inferSelect;
export type Role = typeof roles.$inferSelect;
export type RolePermission = typeof rolePermissions.$inferSelect;
export type UserRole = typeof userRoles.$inferSelect;
export type NewPermission = typeof permissions.$inferInsert;
export type NewRole = typeof roles.$inferInsert;
export type NewRolePermission = typeof rolePermissions.$inferInsert;
export type NewUserRole = typeof userRoles.$inferInsert;