info:
  name: List Tasks
  type: http
  seq: 1
  tags:
    - tasks

http:
  method: GET
  url: "{{base_url}}/tasks"
  auth:
    type: bearer
    token: "{{session_token}}"

runtime:
  scripts:
    - type: tests
      code: |-
        test("status is 200", () => expect(res.status).to.equal(200));

settings:
  encodeUrl: true