// Generated by evlog/vite — do not edit
export {};
declare global {
  const log: import("evlog").Log;
  const createEvlogError: typeof import("evlog").createEvlogError;
  const parseError: typeof import("evlog").parseError;
}