/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as landingTermsRouteImport } from './routes/(landing)/terms'
import { Route as landingStatusRouteImport } from './routes/(landing)/status'
import { Route as landingPrivacyRouteImport } from './routes/(landing)/privacy'
import { Route as landingDocsRouteImport } from './routes/(landing)/docs'
import { Route as landingChangelogRouteImport } from './routes/(landing)/changelog'
import { Route as landingBlogRouteImport } from './routes/(landing)/blog'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as landingDocsIndexRouteImport } from './routes/(landing)/docs/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as landingDocsSplatRouteImport } from './routes/(landing)/docs.$'
import { Route as AuthenticatedDashboardSettingsRouteRouteImport } from './routes/_authenticated/dashboard/settings/route'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/dashboard/users/index'
import { Route as AuthenticatedDashboardTasksIndexRouteImport } from './routes/_authenticated/dashboard/tasks/index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard/settings/index'
import { Route as AuthenticatedDashboardChatsIndexRouteImport } from './routes/_authenticated/dashboard/chats/index'
import { Route as AuthenticatedDashboardAppsIndexRouteImport } from './routes/_authenticated/dashboard/apps/index'
import { Route as AuthenticatedDashboardSettingsNotificationsRouteImport } from './routes/_authenticated/dashboard/settings/notifications'
import { Route as AuthenticatedDashboardSettingsDisplayRouteImport } from './routes/_authenticated/dashboard/settings/display'
import { Route as AuthenticatedDashboardSettingsAppearanceRouteImport } from './routes/_authenticated/dashboard/settings/appearance'
import { Route as AuthenticatedDashboardSettingsAccountRouteImport } from './routes/_authenticated/dashboard/settings/account'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const landingTermsRoute = landingTermsRouteImport.update({
  id: '/(landing)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const landingStatusRoute = landingStatusRouteImport.update({
  id: '/(landing)/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPrivacyRoute = landingPrivacyRouteImport.update({
  id: '/(landing)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const landingDocsRoute = landingDocsRouteImport.update({
  id: '/(landing)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const landingChangelogRoute = landingChangelogRouteImport.update({
  id: '/(landing)/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const landingBlogRoute = landingBlogRouteImport.update({
  id: '/(landing)/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const landingDocsIndexRoute = landingDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingDocsRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const landingDocsSplatRoute = landingDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => landingDocsRoute,
} as any)
const AuthenticatedDashboardSettingsRouteRoute =
  AuthenticatedDashboardSettingsRouteRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTasksIndexRoute =
  AuthenticatedDashboardTasksIndexRouteImport.update({
    id: '/dashboard/tasks/',
    path: '/dashboard/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedDashboardChatsIndexRoute =
  AuthenticatedDashboardChatsIndexRouteImport.update({
    id: '/dashboard/chats/',
    path: '/dashboard/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAppsIndexRoute =
  AuthenticatedDashboardAppsIndexRouteImport.update({
    id: '/dashboard/apps/',
    path: '/dashboard/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsNotificationsRoute =
  AuthenticatedDashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsDisplayRoute =
  AuthenticatedDashboardSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsAppearanceRoute =
  AuthenticatedDashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsAccountRoute =
  AuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/blog': typeof landingBlogRoute
  '/changelog': typeof landingChangelogRoute
  '/docs': typeof landingDocsRouteWithChildren
  '/privacy': typeof landingPrivacyRoute
  '/status': typeof landingStatusRoute
  '/terms': typeof landingTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/docs/$': typeof landingDocsSplatRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/docs/': typeof landingDocsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/dashboard/settings/account': typeof AuthenticatedDashboardSettingsAccountRoute
  '/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/settings/display': typeof AuthenticatedDashboardSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof AuthenticatedDashboardSettingsNotificationsRoute
  '/dashboard/apps/': typeof AuthenticatedDashboardAppsIndexRoute
  '/dashboard/chats/': typeof AuthenticatedDashboardChatsIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/tasks/': typeof AuthenticatedDashboardTasksIndexRoute
  '/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/blog': typeof landingBlogRoute
  '/changelog': typeof landingChangelogRoute
  '/privacy': typeof landingPrivacyRoute
  '/status': typeof landingStatusRoute
  '/terms': typeof landingTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$': typeof landingDocsSplatRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/docs': typeof landingDocsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/dashboard/settings/account': typeof AuthenticatedDashboardSettingsAccountRoute
  '/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/settings/display': typeof AuthenticatedDashboardSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof AuthenticatedDashboardSettingsNotificationsRoute
  '/dashboard/apps': typeof AuthenticatedDashboardAppsIndexRoute
  '/dashboard/chats': typeof AuthenticatedDashboardChatsIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(landing)/blog': typeof landingBlogRoute
  '/(landing)/changelog': typeof landingChangelogRoute
  '/(landing)/docs': typeof landingDocsRouteWithChildren
  '/(landing)/privacy': typeof landingPrivacyRoute
  '/(landing)/status': typeof landingStatusRoute
  '/(landing)/terms': typeof landingTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/(landing)/docs/$': typeof landingDocsSplatRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/(landing)/docs/': typeof landingDocsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/dashboard/settings/account': typeof AuthenticatedDashboardSettingsAccountRoute
  '/_authenticated/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/_authenticated/dashboard/settings/display': typeof AuthenticatedDashboardSettingsDisplayRoute
  '/_authenticated/dashboard/settings/notifications': typeof AuthenticatedDashboardSettingsNotificationsRoute
  '/_authenticated/dashboard/apps/': typeof AuthenticatedDashboardAppsIndexRoute
  '/_authenticated/dashboard/chats/': typeof AuthenticatedDashboardChatsIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/dashboard/tasks/': typeof AuthenticatedDashboardTasksIndexRoute
  '/_authenticated/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/blog'
    | '/changelog'
    | '/docs'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/api/$'
    | '/dashboard/settings'
    | '/docs/$'
    | '/errors/$error'
    | '/docs/'
    | '/dashboard/'
    | '/help-center/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps/'
    | '/dashboard/chats/'
    | '/dashboard/settings/'
    | '/dashboard/tasks/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/blog'
    | '/changelog'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/api/$'
    | '/docs/$'
    | '/errors/$error'
    | '/docs'
    | '/dashboard'
    | '/help-center'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps'
    | '/dashboard/chats'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(landing)/blog'
    | '/(landing)/changelog'
    | '/(landing)/docs'
    | '/(landing)/privacy'
    | '/(landing)/status'
    | '/(landing)/terms'
    | '/api/$'
    | '/_authenticated/dashboard/settings'
    | '/(landing)/docs/$'
    | '/_authenticated/errors/$error'
    | '/(landing)/docs/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help-center/'
    | '/_authenticated/dashboard/settings/account'
    | '/_authenticated/dashboard/settings/appearance'
    | '/_authenticated/dashboard/settings/display'
    | '/_authenticated/dashboard/settings/notifications'
    | '/_authenticated/dashboard/apps/'
    | '/_authenticated/dashboard/chats/'
    | '/_authenticated/dashboard/settings/'
    | '/_authenticated/dashboard/tasks/'
    | '/_authenticated/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  landingBlogRoute: typeof landingBlogRoute
  landingChangelogRoute: typeof landingChangelogRoute
  landingDocsRoute: typeof landingDocsRouteWithChildren
  landingPrivacyRoute: typeof landingPrivacyRoute
  landingStatusRoute: typeof landingStatusRoute
  landingTermsRoute: typeof landingTermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/terms': {
      id: '/(landing)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof landingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/status': {
      id: '/(landing)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof landingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/privacy': {
      id: '/(landing)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof landingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/docs': {
      id: '/(landing)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof landingDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/changelog': {
      id: '/(landing)/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof landingChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/blog': {
      id: '/(landing)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof landingBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(landing)/docs/': {
      id: '/(landing)/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof landingDocsIndexRouteImport
      parentRoute: typeof landingDocsRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(landing)/docs/$': {
      id: '/(landing)/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof landingDocsSplatRouteImport
      parentRoute: typeof landingDocsRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/users/': {
      id: '/_authenticated/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/tasks/': {
      id: '/_authenticated/dashboard/tasks/'
      path: '/dashboard/tasks'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
    '/_authenticated/dashboard/chats/': {
      id: '/_authenticated/dashboard/chats/'
      path: '/dashboard/chats'
      fullPath: '/dashboard/chats/'
      preLoaderRoute: typeof AuthenticatedDashboardChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/apps/': {
      id: '/_authenticated/dashboard/apps/'
      path: '/dashboard/apps'
      fullPath: '/dashboard/apps/'
      preLoaderRoute: typeof AuthenticatedDashboardAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings/notifications': {
      id: '/_authenticated/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
    '/_authenticated/dashboard/settings/display': {
      id: '/_authenticated/dashboard/settings/display'
      path: '/display'
      fullPath: '/dashboard/settings/display'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
    '/_authenticated/dashboard/settings/appearance': {
      id: '/_authenticated/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
    '/_authenticated/dashboard/settings/account': {
      id: '/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteRoute
    }
  }
}

interface AuthenticatedDashboardSettingsRouteRouteChildren {
  AuthenticatedDashboardSettingsAccountRoute: typeof AuthenticatedDashboardSettingsAccountRoute
  AuthenticatedDashboardSettingsAppearanceRoute: typeof AuthenticatedDashboardSettingsAppearanceRoute
  AuthenticatedDashboardSettingsDisplayRoute: typeof AuthenticatedDashboardSettingsDisplayRoute
  AuthenticatedDashboardSettingsNotificationsRoute: typeof AuthenticatedDashboardSettingsNotificationsRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedDashboardSettingsRouteRouteChildren: AuthenticatedDashboardSettingsRouteRouteChildren =
  {
    AuthenticatedDashboardSettingsAccountRoute:
      AuthenticatedDashboardSettingsAccountRoute,
    AuthenticatedDashboardSettingsAppearanceRoute:
      AuthenticatedDashboardSettingsAppearanceRoute,
    AuthenticatedDashboardSettingsDisplayRoute:
      AuthenticatedDashboardSettingsDisplayRoute,
    AuthenticatedDashboardSettingsNotificationsRoute:
      AuthenticatedDashboardSettingsNotificationsRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
  }

const AuthenticatedDashboardSettingsRouteRouteWithChildren =
  AuthenticatedDashboardSettingsRouteRoute._addFileChildren(
    AuthenticatedDashboardSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardSettingsRouteRoute: typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedDashboardAppsIndexRoute: typeof AuthenticatedDashboardAppsIndexRoute
  AuthenticatedDashboardChatsIndexRoute: typeof AuthenticatedDashboardChatsIndexRoute
  AuthenticatedDashboardTasksIndexRoute: typeof AuthenticatedDashboardTasksIndexRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardSettingsRouteRoute:
    AuthenticatedDashboardSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedDashboardAppsIndexRoute: AuthenticatedDashboardAppsIndexRoute,
  AuthenticatedDashboardChatsIndexRoute: AuthenticatedDashboardChatsIndexRoute,
  AuthenticatedDashboardTasksIndexRoute: AuthenticatedDashboardTasksIndexRoute,
  AuthenticatedDashboardUsersIndexRoute: AuthenticatedDashboardUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface landingDocsRouteChildren {
  landingDocsSplatRoute: typeof landingDocsSplatRoute
  landingDocsIndexRoute: typeof landingDocsIndexRoute
}

const landingDocsRouteChildren: landingDocsRouteChildren = {
  landingDocsSplatRoute: landingDocsSplatRoute,
  landingDocsIndexRoute: landingDocsIndexRoute,
}

const landingDocsRouteWithChildren = landingDocsRoute._addFileChildren(
  landingDocsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  landingBlogRoute: landingBlogRoute,
  landingChangelogRoute: landingChangelogRoute,
  landingDocsRoute: landingDocsRouteWithChildren,
  landingPrivacyRoute: landingPrivacyRoute,
  landingStatusRoute: landingStatusRoute,
  landingTermsRoute: landingTermsRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
